### ISSUE TITLE
sbt test fails

### ISSUE THREAD

**Issue by radugm** [hussachai/play-scalajs-showcase#9]
radus-MacBook-Pro-2:play-scalajs-showcase radu$ sbt test
[info] Loading project definition from /Users/radu/github/play-scalajs-showcase/project
[info] Set current project to play-scalajs-showcase (in build file:/Users/radu/github/play-scalajs-showcase/)
[info] Set current project to exampleServer (in build file:/Users/radu/github/play-scalajs-showcase/)
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  \* org.webjars:jquery:1.11.1 -> 2.1.4
[warn] Run 'evicted' to see detailed eviction warnings
java.lang.RuntimeException: Exception while running JS code: TypeError: Cannot call method "createElement" of undefined (/Users/radu/.ivy2/cache/org.webjars/jquery/jars/jquery-2.1.3.jar#META-INF/resources/webjars/jquery/2.1.3/jquery.js#887)
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:173)
    at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:62)
    at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:68)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$48.apply(ScalaJSPluginInternal.scala:574)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$48.apply(ScalaJSPluginInternal.scala:559)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](exampleClient/test:loadedTestFrameworks) Exception while running JS code: TypeError: Cannot call method "createElement" of undefined (/Users/radu/.ivy2/cache/org.webjars/jquery/jars/jquery-2.1.3.jar#META-INF/resources/webjars/jquery/2.1.3/jquery.js#887)
[error] Total time: 3 s, completed Mar 10, 2016 1:35:20 PM

**Comment by hussachai** [comment]
Thank you for creating an issue. I didn't have to look into it. It would be awesome if you can fix it and share :)
